### ISSUE TITLE
Cannot find module './build/Release/scrypt'

### ISSUE THREAD

**Issue by benjyz** [RadarTech/sdk-bot-example#9]
with node8 on ubuntu and mac I get

`Error: Cannot find module './build/Release/scrypt'`

not sure if this is related to this package as its deprecated
https://github.com/barrysteyn/node-scrypt

**Comment by smithki** [comment]
`scrypt` is not required in `package.json` for the example to run. It is a dependency of a dependency and that's why it gets installed. However, there are some environmental quirks that commonly occur with these packages. Here's some steps to try:

1. Ensure you are using Node `v8.x` (I am using `v8.15.0` when running this app)
1. Remove `node_modules`
3. Run `npm install`
4. Note the console output of the `node-pre-gyp install` command.
5. If there are errors, whether or not `npm install` completes successfuly, check to ensure the `node-hid` dependencies are installed on your machine: https://github.com/node-hid/node-hid#compiling-from-source (if issues persist, there are some additional troubleshooting steps here: https://github.com/node-hid/node-hid/issues/144).

Feel free to re-open this issue if you need additional troubleshooting help.
